name: Pull Request
on:
  pull_request:
    branches: [main]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
      JWT_SECRET: secret
    steps:
      - name: Setup GHA
        uses: actions/checkout@v2
      - name: Install modules
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Run Unit Tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
